### ISSUE TITLE
Do you have any docs for this?

### ISSUE THREAD

**Issue by argman** [muschellij2/CT_BET#1]
I find this interesting project, but no docs..

**Comment by muschellij2** [comment]
The paper is located here: http://www.sciencedirect.com/science/article/pii/S1053811915002700

**Comment by argman** [comment]
thks, but if i want to use this to extract brain, is there any function like extract(ct images)

**Comment by muschellij2** [comment]
http://bit.ly/CTBET_RCODE
http://bit.ly/CTBET_BASH

You need FSL installed

John

**Comment by muschellij2** [comment]
CT_Skull_Strip("filename.nii.gz")

John

**Comment by argman** [comment]
tks for fast reply, i will try it.
